
rvm:
  - 2.7.2

services:
  - postgresql

addons:
  apt:
    update: true
    packages:
      - moreutils 

before_install:
  - nvm install node
  
os:
  - linux

env:
  global:
    secure: "Cu1fa16qIYsvMnat8MLJcsCAhF5sg1t0e/znTRVfeLY+4t345oM4/Ut/1xz6+CDcqoyio5ZEWFg4gqptV5cwV2RPoQEuRe8LyKicEQYBVLncQZ9GBjDF5kgSkxiRFKsim8ghCsVpFdn6U7HwuXqs0zy1Bbsv3KVV/1i3sRSsXesZWTC69nBjiBeVbMI+mOThfW+lpX8nncsS1t8zIH6uGkq2uDIT8B0LaeIepNXLyoKf/SKWFuok3BoVeeCSjyVWIr4kgeB2A7K/vhA6j4+UVsIzUW3ZswXN4xAN7/sLiyyei97138fv1Ns55ajDNakLCOLgesdsdS/bK25A338eoZGI/YGdZTFgpzXXzkAlJqLp4IXPjxHLjs/69Gs0T8guz7ktDqzyt0phVdYaBboNmV3O8Z83PvwkUtjLw0rORwadD0488Mps65JGnGoIpMr6ikJoGnSZvcipTnDawwAiQn03ocFaLhqeRRheBTTbvpPNCc1rVr2CUL2LNz88hCeYn8Iw870WAiQICPt8SvW85uKQqul1buYQI/WGDVVuyQsrwWsRe1BluY2rqrJGXPmOOdTffMJR1REXtOyWsPeHMgYwZLLfQcGmHc8hFLV+1HBx0j1pCCxBM4uGfRnOO4PkumN9m72PYcpUgLuI3Oj+YPsIR771MLAaEy6XZ0vx0+4="
  
script:
  - node --version
  - ./create-rails-app
