
rvm:
  - 2.7.2

services:
  - postgresql

addons:
  apt:
    update: true
    packages:
      - moreutils 

before_install:
  - nvm install node
  
os:
  - linux
  
script:
  - node --version
  - ./create-rails-app
