
rvm:
  - 3.0.1

services:
  - postgresql

addons:
  apt:
    update: true
    packages:
      - moreutils 

before_install:
  - nvm install node
  
os:
  - linux

env:
  global:
    secure: "bNbonI4cgBrsiev4+Lt/+1gLNXqMX6k1YRmaSG9CPgimXRRrcBye5AtMcT7IQPyGKQyAr82keEWyIOwkt18kcROW63ucKltv/7Ts6KQKDi7DF4FyvmfdGBYcSpNi+7Ezp5or/z4swxBNc/JHDL1ZQgWcejJ78coqa66ia2c6UeRMFgTsVGQSwhyeTsxHdRcCS0yztf9w7rwKWEaWwW/53iVbkbXRzV1JWhAVU5Wp3UiLZl+XKUP23DE8BxUNsXLigHnKxKMoHNDhmb2mTfrLMsPLyiJ8QBHUOmCWHgW8b+YOby964sIyxKGuKfwv8i9uAckgn9kM+8eRX5Fs8Y6jSkggVmJSh293C8JLJ/8DuoDMTZ7ztJ35bIbfIoree+Hh8Sbc7+i8GsCzeDwRII5V9w0eo5b/1tEInq/JlNq74wL8tERd+PRsUd17t4fjceSX7874q4LyotRdD35AeV4mpuBuPTBVwj2chtHAaPYb69Um2ku52PXTCdFgvT/nas8Wh8JWMIpslkwQ+LwWMN2CglJ7uL2Q1wZD+xSqEr7NtJ6ErYUFm2ehf1avMQCPstCQM7mfcJW0vg/ICCdP7WzwpcJB2fonBTPGhFUNOPASl3u8n8WiM40u/IKlw6ldMM9cnswj73bM16+FaO7sOKmvOh894WWmvLtk/KCYT5SiDvs="
  
script:
  - node --version
  - ./create-rails-app
