rvm:
  - __REPLACEME1__

services:
  - postgresql

before_install:
  - nvm install node
  
os:
  - linux

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - yarn install
  - bundle install
  - rake db:test:prepare
  - bundle exec rails test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
