#!/bin/bash

RAILS_VERSION="7-0-stable"
BOOTSTRAP_VERSION="5.1"

download() {
  git clone -b 7-0-stable --single-branch https://github.com/rails/rails /tmp/rails
}

generate() {
  pushd /tmp/rails
  bundle install &>/dev/null
  bundle exec railties/exe/rails new /tmp/created-rails-app --dev --database=postgresql >/dev/null
  cd /tmp/created-rails-app
  commit "Did generate()"
  popd
}

# repoint gemfile to github rails/rails
repoint() {
  pushd /tmp/created-rails-app
  sed -i "/^gem \"rails/c\REMOVED" Gemfile # remove line
  replacement="gem 'rails', :github => 'rails/rails', :branch => '7-0-stable'"
  sed -i "/^REMOVED/c\\$replacement" Gemfile # add back line
  rm Gemfile.lock
  bundle install &>/dev/null
  bundle lock --add-platform ruby # this was needed because ci runs in linux
  ./bin/setup
  commit "Did repoint()"
  popd
}

# adds devise gem
devise() {
  pushd /tmp/created-rails-app
  bundle add devise --git "https://github.com/heartcombo/devise" --branch "main" &>/dev/null
  bundle install &>/dev/null
  ./bin/rails generate devise:install
  ./bin/rails generate devise User
  ./bin/rails db:migrate
  sed -i -e 's/^/# /' test/fixtures/users.yml # stackoverflow/a/51102255
  commit "Did devise()"
  popd
}

bootstrap() {
  pushd /tmp/created-rails-app

  (cd /tmp/ && curl -s -O https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css)
  sed -i 's/body/.bootstrap-signin-example-wrapper/g' /tmp/signin.css

  (cd /tmp/ && curl -s -O https://raw.githubusercontent.com/twbs/bootstrap/main/site/content/docs/5.1/examples/sign-in/index.html)
  mkdir -p app/views/devise/sessions
  cp /tmp/index.html app/views/devise/sessions/new.html.erb
  sed -i 1,9d app/views/devise/sessions/new.html.erb
  sed -i '1s/^/<div class="bootstrap-signin-example-wrapper text-center">\n/' app/views/devise/sessions/new.html.erb
  sed -i -e '$a</div>' app/views/devise/sessions/new.html.erb
  sed -i 's/{{< year >}}/2022/g' app/views/devise/sessions/new.html.erb


  str='<img class="mb-4" src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">'
  sed -i "s@.*bootstrap-logo.svg.*@$str@" app/views/devise/sessions/new.html.erb
  echo '<style>' >> app/views/devise/sessions/new.html.erb
  cat /tmp/signin.css >> app/views/devise/sessions/new.html.erb
  echo '</style>' >> app/views/devise/sessions/new.html.erb

  # use rails form
  # str='<% end %>'
  perl -pi.bak -e 's/<\/form>/<% end %>/g' app/views/devise/sessions/new.html.erb
  rm app/views/devise/sessions/new.html.erb.bak
  str='  <%= form_for(resource, as: resource_name, url: session_path(resource_name), data: { turbo: false }) do |f| %>'
  sed -i "s@.*<form.*@$str@" app/views/devise/sessions/new.html.erb

  cd /tmp/
  git clone git@github.com:la-ruby/bootstrap.git
  cd /tmp/bootstrap
  npm install &>/dev/null
  npm run dist &>/dev/null
  cp dist/js/bootstrap.bundle.js.map /tmp/created-rails-app/public/
  cp dist/js/bootstrap.bundle.js /tmp/created-rails-app/public/
  cp dist/css/bootstrap.css.map /tmp/created-rails-app/app/assets/stylesheets/
  cp dist/css/bootstrap.css /tmp/created-rails-app/app/assets/stylesheets/
  str='   <script src="/bootstrap.bundle.js"></script>'
  sed -i '/\/head.*/i\ '"$str"'' /tmp/created-rails-app/app/views/layouts/application.html.erb

  cd /tmp/created-rails-app
  commit "Did bootstrap()"
  popd
}

# Basic setup for rails flash messages
flash() {
  pushd /tmp/created-rails-app
  cp ~/work/create-rails-app/create-rails-app/templates/app/views/_flashie.html.erb app/views/_flashie.html.erb
  str='   <%= render "/flashie" %>'
  sed -i '/\.*<body.*/a\ '"$str"'' /tmp/created-rails-app/app/views/layouts/application.html.erb
  commit "Did flash()"
  popd
}

# should output: Coverage report generated ... 1328 / 1328 LOC (100.0%) covered.
# when you do COVERAGE=1 ./bin/rails test
simplecov() {
  pushd /tmp/created-rails-app
  echo "gem 'simplecov', require: false, group: :test" >> Gemfile
  bundle install &>/dev/null
  sleep 1
  echo where am i
  pwd
  ls -la ~/work/create-rails-app/
  sleep 1
  cat /home/runner/work/create-rails-app/create-rails-app/templates/test/test_helper.rb.tt test/test_helper.rb > /tmp/file3
  sleep 1
  mv /tmp/file3 test/test_helper.rb
  cat test/test_helper.rb
  sleep 1
  commit "Did simplecov()"
  popd
}

# sets up automated testing (ci) via github actions
ci() {
  pushd /tmp/created-rails-app
  mkdir .github/workflows/
  cp ~/work/create-rails-app/create-rails-app/templates/.github/workflows/verify.yml .github/workflows/
  commit "Did ci()"
  popd
}



upload() {
  # Temporary - for troubleshooting
  pushd /tmp/created-rails-app
  git remote add bugDemo git@github.com:la-ruby/created-rails-app.git
  git checkout -b bugDemo
  git push -f bugDemo bugDemo
  git checkout main

  git clone git@github.com:la-ruby/created-rails-app.git /tmp/downloaded-rails-app
  cd /tmp/downloaded-rails-app/
  find -not -path "./.git/*" -not -name ".git" -delete
  rsync --stats -aP --exclude='.git/' --exclude='node_modules/*' /tmp/created-rails-app/ /tmp/downloaded-rails-app/ &>/dev/null

  git add --all
  git commit -m "Updates for $(date +%D)"
  git push origin main
  popd
}

commit() {
  git add --all &>/dev/null
  git commit -m "$1" &>/dev/null
}

main() {
  # Some Prereqs - git setup
  git config --global init.defaultBranch main
  git config --global user.email "example@example.com"
  git config --global user.name "Sam Bot"

  download
  generate
  repoint
  devise
  bootstrap
  flash
  simplecov
  ci
  upload
}

main
