#!/bin/bash

download() {
  git clone -b 7-0-stable --single-branch https://github.com/rails/rails /tmp/rails
}

generate() {
  cd /tmp/rails
  bundle install >/dev/null
  bundle exec railties/exe/rails new /tmp/created-rails-app --dev --database=postgresql >/dev/null
}

# repoint gemfile to github rails/rails
repoint() {
  cd /tmp/created-rails-app
  sed -i "/^gem \"rails/c\REMOVED" Gemfile # remove line
  replacement="gem 'rails', :github => 'rails/rails', :branch => '7-0-stable'"
  sed -i "/^REMOVED/c\\$replacement" Gemfile # add back line
  rm Gemfile.lock
  bundle install
  bundle lock --add-platform ruby # this was needed because ci runs in linux
}

# adds devise gem
devise() {
  cd /tmp/created-rails-app
  bundle add devise --git "https://github.com/heartcombo/devise" --branch "main"
  bundle install
  ./bin/rails generate devise:install
}

upload() {
  git clone git@github.com:la-ruby/created-rails-app.git /tmp/downloaded-rails-app
  cd /tmp/downloaded-rails-app/
  find -not -path "./.git/*" -not -name ".git" -delete
  rsync --stats -aP --exclude='.git/' --exclude='node_modules/*' /tmp/created-rails-app/ /tmp/downloaded-rails-app/
  git config user.email "example@example.com"
  git config --global user.name "Sam Bot"
  git add --all
  git commit -m "Updates for $(date +%D)"
  git push origin main
}


main() {
  download
  generate
  repoint
  devise
  upload
}

main
