#! /usr/bin/env expect

# set timeout 5

spawn ./bin/rails stimulus_reflex:install
sleep 5
expect -re ".*or type a different path.*"
send -- "\n"
sleep 5
expect -re ".*It looks like you're using esbuild as your bundler. Is that correct? (Y/n).*"
send -- "y\n"
sleep 40
expect -re ".*broadcaster.rb.*"

# needed?
sleep 1
send -- "a\n"
sleep 1
send -- "a\n"


sleep 20
expect -re ".*Join over 2000 StimulusReflex developers on Discord(.*)"
expect eof
